version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/rust:1.55.0
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout
      - run: sudo apt-get -y update &&
             sudo apt-get -y install gcc g++ git cmake clang
      - run: git submodule update --init --recursive
      - run: cargo test

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "cargo_build_test"
  cargo_build_test:
    jobs:
      - build_and_test